
export const movies = [
{
title: "Toy Story",
genre: "comédia",
ageRating: livre,
synopsis: "O aniversário de Andy está chegando e os brinquedos estão nervosos. Afinal de contas, eles temem que um novo brinquedo possa substituí-los. Liderados por Woody, um caubói que é também o brinquedo predileto de Andy, eles montam uma escuta que lhes permite saber dos presentes ganhos.
",
trailer: "https://youtu.be/v-PjgYDrg70?feature=shared
"
},
{
title: "Shrek",
genre: "Comédia",
ageRating: 10,
synopsis: "Em um pântano distante vive Shrek (Mike Myers), um ogro solitário que vê, sem mais nem menos, sua vida ser invadida por uma série de personagens de contos de fada, como três ratos cegos, um grande e malvado lobo e ainda três porcos que não têm um lugar onde morar. Todos eles foram expulsos de seus lares pelo maligno Lorde Farquaad (John Lithgow).
",
trailer: "https://youtu.be/CwXOrWvPBPk?feature=shared
"
},
{
title: "Escola de Rock",
genre: "Comédia",
ageRating: 12,
synopsis: "Dewey Finn (Jack Black) é um músico que acaba de ser demitido de sua banda. Cheio de dívidas para pagar e sem ter o que fazer, ele aceita dar aulas como professor substituto em uma escola particular de disciplina rígida. Logo Dewey se torna um exemplo para seus alunos, sendo que alguns deles se juntam ao professor para montar uma banda local, sem o conhecimento de seus pais.
",
trailer: "https://youtu.be/TExoc0MG4I4?feature=shared
"
},
{
title: "As Branquelas",
genre: "Comédia",
ageRating: 14,
synopsis: "Em As Branquelas, os irmãos Marcus (Marlon Wayans) e Kevin Copeland (Shawn Wayans) são detetives do FBI que estão com problemas no trabalho. A última investigação da dupla foi um grande fracasso e eles estão sob a ameaça de serem demitidos.
",
trailer: "https://youtu.be/seoJIPLLWp0?feature=shared
"
},
{
title: "Deadpool",
genre: "Comédia",
ageRating: 16,
synopsis: "Ex-militar e mercenário, Wade Wilson (Ryan Reynolds) é diagnosticado com câncer em estado terminal, porém encontra uma possibilidade de cura em uma sinistra experiência científica. Recuperado, com poderes e um incomum senso de humor, ele torna-se Deadpool e busca vingança contra o homem que destruiu sua vida.",
trailer: "https://youtu.be/Xithigfg7dA?feature=shared
"
},
{
title: "Os Incríveis",
genre: “Ação",
ageRating: livre,
synopsis: "Uma família de super-heróis tenta levar uma vida normal, mas é chamada de volta à ação quando um novo vilão ameaça a paz mundial. Juntos, eles aprendem a importância do trabalho em equipe.

",
trailer: "https://youtu.be/-UaGUdNJdRQ?feature=shared"

},
{
title: "Homem-aranha no aranha verso",{
genre: "Ação",
ageRating: 10,
synopsis: "Miles Morales descobre que há vários universos com diferentes versões do Homem-Aranha. Ele precisa aprender a usar seus novos poderes para salvar sua cidade e o multiverso.
",
trailer: "https://youtu.be/SS6ABPkfmBE?feature=shared"

},
{
title: "Pantera Negra",
genre: "Ação",
ageRating: 12,
synopsis: "T'Challa retorna a Wakanda após a morte de seu pai para assumir o trono como Pantera Negra. Porém, ele enfrenta desafios de um inimigo com ambições para governar o mundo.
",
trailer: "https://youtu.be/3PJA_uXj_Zk?feature=shared"
},
{
title: "Vingadores: Guerra infinita",
genre: "Ação",
ageRating: 14,
synopsis: "Os Vingadores se unem para enfrentar Thanos, um poderoso inimigo que busca destruir metade do universo coletando as Joias do Infinito.
",
trailer: "https://youtu.be/t_ULBP6V9bg?feature=shared"
},
{
title: "Jhon Wick",
genre: "Ação",
ageRating: 16,
synopsis: "Após a morte de sua esposa, John Wick volta ao mundo do crime para se vingar de gangsters que roubaram seu carro e mataram seu cachorro, o último presente de sua amada.
",
trailer: "https://youtu.be/C0BMx-qxsP4?feature=shared"
},
{
title: "",
genre: Suspense”,
ageRating: livre,
synopsis: "Três amigos descobrem que uma casa no bairro é viva e perigosa. Eles precisam desvendar o mistério antes que ela cause mais estragos.
",
trailer: "https://youtu.be/4Qb-hHqwXJA?feature=shared"
},
{
title: "O fantasma de Scrooge",
genre: "Suspense",
ageRating: 10,
synopsis: "Um velho avarento é visitado por três espíritos na véspera de Natal que o fazem confrontar seu passado, presente e futuro, levando-o a mudar suas atitudes",
trailer: "https://youtu.be/GvvtPWOMEYk?feature=shared"
},
{
title: "Um Lugar Silencioso",
genre: "Suspense",
ageRating: 12,
synopsis: "Em um mundo pós-apocalíptico, uma família tenta sobreviver em silêncio absoluto para evitar monstros sensíveis ao som que caçam qualquer barulho.
",
trailer: "https://youtu.be/ENocUCWoGHA?feature=shared"
},
{
title: "O Homem Invisível ",
genre: "",
ageRating: 14,
synopsis: "Cecília tenta escapar de um relacionamento abusivo, mas começa a ser perseguida por uma figura invisível, acreditando que é seu ex, que supostamente morreu.
",
trailer: "https://youtu.be/L91CO7wOqVw?feature=shared"
},
{
title: "Hereditário",
genre: Suspense"",
ageRating: 16,
synopsis: "Após a morte de sua mãe, uma família começa a descobrir segredos sombrios e aterrorizantes. Eventos sobrenaturais colocam todos em um ciclo de horror psicológico intenso.
",
trailer: "https://youtu.be/Ui13PlmyZhQ?feature=shared"
},
{
title: "A Bela e a Fera",
genre: "Romance",
ageRating: livre,
synopsis: "Uma jovem corajosa troca sua liberdade para salvar seu pai e acaba se apaixonando por uma fera misteriosa, que guarda um segredo que pode mudar suas vidas.
",
trailer: "https://youtu.be/Ui13PlmyZhQ?feature=shared"
},
{
title: "Encantada",
genre: "Romance",
ageRating: 10,
synopsis: "Giselle, uma princesa de conto de fadas, é transportada para o mundo real. Perdida em Nova York, ela descobre um novo tipo de amor enquanto tenta voltar para casa",
trailer: "https://youtu.be/IJwUFq8uOr0?feature=shared"
},
{
title: "SimplesmenteAcontece",
genre: "Romance",
ageRating: 12,
synopsis: "Melhores amigos desde a infância, Rosie e Alex enfrentam anos de desencontros e situações que testam o verdadeiro significado de sua relação.",
trailer: "https://youtu.be/ZUqU9SQOt10?feature=shared"
},
{
title: "Como Eu Era Antes de Você",
genre: "Romance",
ageRating: 14,
synopsis: "Louisa, uma jovem otimista, aceita o emprego de cuidar de Will, um homem tetraplégico. Apesar das diferenças, eles desenvolvem um relacionamento que muda suas vidas para sempre.
",
trailer: "https://youtu.be/PnqUs3xiAVI?feature=shared"
},
{
title: "Orgulho e Preconceito",
genre: "Romance",
ageRating: 16,
synopsis: "Elizabeth Bennet, uma jovem inteligente e independente, enfrenta conflitos de classe, orgulho e preconceitos enquanto se apaixona pelo reservado Sr. Darcy.
",
trailer: "https://youtu.be/Ur_DIHs92NM?feature=shared"
},
{
title: "A Procura Da Felicidade ",
genre: "Drama",
ageRating: livre,
synopsis: "Chris Gardner enfrenta dificuldades financeiras enquanto luta para criar seu filho pequeno. Determinado a mudar sua vida, ele se esforça para conquistar um emprego como corretor da bolsa
",
trailer: "https://youtu.be/yHgiEADa5M8?feature=shared"
},
{
title: "Extraordinário",
genre: "Drama",
ageRating: 10,
synopsis: "Auggie Pullman, um menino com deformidades faciais, entra pela primeira vez em uma escola convencional. Ele enfrenta desafios de aceitação e amizade enquanto inspira aqueles ao seu redor.
",
trailer: "https://youtu.be/7lyJtY_TPvk?feature=shared"
},
{
title: "A Vida Bela",
genre: "Drama",
ageRating: 12,
synopsis: "Guido, um homem otimista, usa seu humor e imaginação para proteger seu filho da dura realidade de um campo de concentração durante a Segunda Guerra Mundial.
",
trailer: "https://youtu.be/2MPGncRcZwk?feature=shared"
},
{
title: "O Curioso Caso De Benjamin Button",
genre: "Drama",
ageRating: 14,
synopsis: "Benjamin nasce com uma condição única: ele envelhece ao contrário. Ao longo de sua vida, ele enfrenta as complexidades do amor e das relações enquanto vive de maneira fora do comum.
",
trailer: "https://youtu.be/p8ucIL2tLLo?feature=shared"
},
{
title: "Réquiem para um Sonho",
genre: "Drama",
ageRating: 16,
synopsis: "Este impactante drama explora a vida de quatro personagens que lutam contra o vício e as consequências devastadoras de seus sonhos e escolhas.
",
trailer: "https://youtu.be/kJ39qXjKLWs?feature=shared"
},
{
title: "Procurando Nemo",
genre: "Animação",
ageRating: livre,
synopsis: "Quando o pequeno peixe-palhaço Nemo é capturado por mergulhadores, seu pai, Marlin, embarca em uma emocionante jornada pelo oceano para resgatá-lo, com a ajuda da esquecida Dory.
",
trailer: "https://youtu.be/9oQ628Seb9w?feature=shared"
},
{
title: "Valente",
genre: "Animação",
ageRating: 10,
synopsis: " Merida, uma princesa rebelde, desafia as tradições de sua família e, ao fazer um pedido impulsivo, precisa lidar com as consequências para salvar seu reino e sua mãe.
",
trailer: "https://youtu.be/vHOC1Kd_zhw?feature=shared"
},
{
title: "A Viagem de Chihiro",
genre: "Animação",
ageRating: 12,
synopsis: "Chihiro, uma garota de 10 anos, se perde em um mundo mágico habitado por espíritos e deuses. Para salvar seus pais, transformados em porcos, ela precisa trabalhar em uma casa de banhos espiritual.
",
trailer: "https://youtu.be/fDUFP7EeXLE?feature=shared"
},
{
title: "Castelo Animado",
genre: "Animação",
ageRating: 14,
synopsis: "Sophie, uma jovem transformada em idosa por um feitiço, embarca em uma jornada para encontrar o misterioso mago Howl e desfazer o encantamento em um mundo repleto de magia e guerra.",
trailer: "https://youtu.be/iM9pZ01J7Lc?feature=shared"
},
{
title: "Ilha dos Cachorros",
genre: "Animação 
",
ageRating: 16,
synopsis: "Em um Japão distópico, um menino embarca em uma aventura para resgatar seu cachorro exilado em uma ilha infestada de cães abandonados, enfrentando desafios emocionais e políticos.
",
trailer: "https://youtu.be/WbZUIusb_6E?feature=shared"
},
{
title: "Big Hero 6",
genre: "Ficção Científica",
ageRating: livre,
synopsis: "Hiro, um jovem prodígio da robótica, junta-se ao adorável robô Baymax e seus amigos para formar uma equipe de heróis e enfrentar uma conspiração tecnológica na futurista cidade de San Fransokyo.",
trailer: "https://youtu.be/jwbHKtEsOeM?feature=shared"
},
{
title: "Zathura: Uma Aventura Espacial",
genre: "Ficção Científica",
ageRating: 10,
synopsis: "Dois irmãos descobrem um jogo de tabuleiro mágico que os transporta para o espaço. Enquanto enfrentam desafios perigosos, eles precisam trabalhar juntos para terminar o jogo e voltar para casa",
trailer: "https://youtu.be/zNxm_obDpNU?feature=shared"
},
{
title: "O Doador de Memórias",
genre: "Ficção Científica",
ageRating: 12,
synopsis: "Em uma sociedade aparentemente perfeita, Jonas descobre verdades sombrias sobre sua comunidade ao receber memórias do passado com o mentor conhecido como O Doador.
",
trailer: "https://youtu.be/FtNpOIjmiDY?feature=shared
"
},
{
title: "A Chegada",
genre: "Ficção Científica",
ageRating: 14,
synopsis: "Quando naves alienígenas pousam na Terra, uma linguista é chamada para decifrar sua linguagem e descobrir se vieram em paz ou representam uma ameaça, enquanto enfrenta questões de tempo e destino.
",
trailer: "https://youtu.be/isWwUJf4KEA?feature=shared"
},
{
title: "Blade Runner 2049",
genre: "Ficção Científica",
ageRating: 16,
synopsis: K, um caçador de androides, descobre um segredo enterrado há décadas que pode mudar o futuro da humanidade. Sua investigação o leva a Rick Deckard, um caçador de andróides desaparecido há 30 anos.
"",
trailer: "https://youtu.be/xGwe7D0RKWc?feature=shared"
}
